# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cebbd911a0d94343a9d7bb73dec8795be344fa79bc84f0cc713e62b77b2def6ccac840631196d790f98897b71f1309f3ef58c89dc5f9d2f878a348b639f32b48

test:
  secret_key_base: 848e9c2cbcfd9d696bac82871b42fc19d14227f02941cc77ac50c408e2cb1f935f6a653efa5c35d1e5700e5a8dda48556cb246a0528469d2ccb7f4d12eed9c0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
